### ISSUE TITLE
Subject: Maintenance Status and Support for F1-F12 Key Press Events

### ISSUE THREAD

**Issue by keyboard2005** [node-3d/iohook-raub#1]
Hello,

I would like to inquire about the current maintenance status of this project. It's the only package I've found that supports the latest version of Electron and Node.js for global keyboard and mouse events. However, I've encountered a minor issue - the F1 to F12 keys do not trigger press events, only release events are detected. Is it possible to address and fix this issue?

Thank you for your assistance.

**Comment by keyboard2005** [comment]
After several days of searching and trying out more than a dozen keyboard and mouse hook libraries, your project is the only one I found that supports the latest versions of Node.js and Electron. I'm very grateful for your contribution.

**Comment by raub** [comment]
Hello, I will look into that. The maintenance status is "I'm still here"

**Comment by raub** [comment]
Ok, please try re-installing the module. No version changes needed - in fact, it will only download the updated [binary](https://github.com/node-3d/iohook-raub/releases/tag/0.0.1).

The issue was a bit deeper than just F-keys and involved bogus threading/lifetimes logic. But now it seems to be working fine.

**Comment by Senails** [comment]
Thank you for supporting this project, I am very grateful to you too

**Comment by keyboard2005** [comment]
It's running well now, thanks again for supporting
